language: "python"
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.9-dev"  # 3.9 development branch
  # - "nightly"  # nightly build

branches:
  only:
  - master
  - staging
  - /^\d+\.\d+\.\d+.*$/  # tags

stages:
  - test
  - deploy

install:
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install --no-root -v

jobs:
  include:
    - stage: test
      script: poetry run coverage run -m pytest iregex
      after_success:
        - poetry run codecov
    - script: poetry run mypy iregex
    - script: poetry run flake8 iregex

    - stage: deploy
      script: skip
      before_deploy:
        - poetry config pypi-token.pypi $PYPI_PASSWORD
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
          repo: ryanpeach/py_idiomatic_regex
          branch: master
    - script:
        - poetry run make github
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN
        keep-history: true
        local_dir: docs
        on:
          tags: true
          repo: ryanpeach/py_idiomatic_regex
          branch: master
