language: "python"
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.9-dev"  # 3.9 development branch
  # - "nightly"  # nightly build

branches:
  only:
  - master
  - staging
  - /^\d+\.\d+\.\d+.*$/  # tags

stages:
  - test
  - deploy

install:
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install --no-root -v

jobs:
  include:
    - stage: test
      script: poetry run coverage run -m pytest iregex
      after_success:
        - poetry run codecov
    - script: poetry run mypy iregex
    - script: poetry run flake8 iregex

    - stage: deploy
      script: skip
      before_deploy:
        - poetry config pypi-token.pypi $PYPI_PASSWORD
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
          repo: ryanpeach/py_idiomatic_regex
          branch: master
    - before_script:
        - poetry install -v
      script:
        - poetry run make github
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git checkout -b docs
        - git add docs/
        - git commit --message "Travis documentation build: $TRAVIS_BUILD_NUMBER"
        - git remote add origin-pages https://${GITHUB_TOKEN}@github.com/ryanpeach/py_idiomatic_regex.git > /dev/null 2>&1
      deploy:
        provider: script
        skip_cleanup: true
        script: git push --quiet --set-upstream origin-pages docs
        on:
          tags: true
          repo: ryanpeach/py_idiomatic_regex
          branch: master
